name: Generate IGDB BFF

# QUAND LANCER LE WORKFLOW ?
on:
  schedule:
    - cron: '17 2 * * *'  # Automatiquement tous les jours à 3h00 du matin (UTC)
  workflow_dispatch:     # Permet d'afficher le bouton pour le lancer manuellement
  push:
    branches:
      - main             # (ou 'master' selon le nom de ta branche principale)

# PERMISSIONS REQUISES
permissions:
  contents: write        # Indispensable pour que le bot puisse créer la branche gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run BFF script
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
